main:
  - name: People
    url: people
    weight: 10
  - name: Events
    url: event
    weight: 20
  - name: Seminars
    parent: Events
    url: /event/#seminars
    weight: 10
  - name: Conferences
    parent: Events
    url: /event/#conferences
    weight: 20
  - name: Research
    url: publication
    weight: 30
  - name: Recent preprints
    parent: Research
    url: /publication/#preprints
    weight: 10
  - name: Selected publications
    parent: Research
    url: /publication/#spubs
    weight: 20
  - name: Editorial service
    parent: Research
    url: /publication/#editorial
    weight: 30
  - name: PhD Studies
    url: phd
    weight: 40
  - name: Jobs
    url: jobs
    weight: 50