backend:
  name: github
  repo: pzwiernik/upf-statistics   # owner/repo
  branch: main                    # default branch
  auth_type: implicit
  app_id: Ov23liH7FdORtpnUHkkT    # 20-char GitHub Client ID

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: people
    label: People
    folder: content/authors
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Name, name: title, widget: string}
      - {label: Role, name: role, widget: string}