backend:
  name: github
  repo: pzwiernik/upf-statistics        # owner/repo
  branch: main                          # or master
  auth_type: implicit
  app_id: Ov23liH7FdORtpnUHkkT         # paste the ID from your GitHub OAuth app

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "people"
    label: "People"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "User Groups", name: "user_groups", widget: "list"}
  # add more collections later as needed