name: Update Publications from Google Scholar

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:     # Manual trigger

permissions:
  contents: write        # Needed for commit & push

jobs:
  scrape_publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install scholarly
        run: |
          python -m pip install --upgrade pip
          pip install scholarly

      - name: Run Publication Scraper
        run: python scripts/update_publications.py

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/publication/
          git commit -m "Auto-update publications from Google Scholar" || echo "No changes to commit"
          git push