name: Update Publications

on:
  schedule:
    - cron: '0 3 * * 1'        # every Monday 03:00 UTC (adjust as you like)
  workflow_dispatch:           # manual trigger button

permissions:
  contents: write              # so we can push changes

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install scholarly PyYAML

      - name: Run scraper
        id: scraper
        run: |
          python scripts/update_publications.py > scraper_output.txt
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat scraper_output.txt)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit & push changes
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/publication/
          git diff --cached --quiet || git commit -m "📚 Auto-update publications"
          git push

      # ───── OPTIONAL E-MAIL NOTIFICATION ─────
      - name: Send confirmation mail
        if: always()           # run even if no new files
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          subject: "Publication update – ${{ github.repository }} – ${{ job.status }}"
          to: pzwiernik@upf.edu
          from: GitHub Actions <no-reply@github.com>
          content_type: text
          body: |
            Scraper run: ${{ github.run_number }}
            Status: ${{ job.status }}

            Latest log:
            ${{ steps.scraper.outputs.log }}